# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totest', '0013_auto_20160505_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmmockpaydata',
            name='crmmemberid',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
